### ISSUE TITLE
Cannot create new Unit in CMS

### ISSUE THREAD

**Issue by laithmassoud** [Abstract-Tech/derex.openedx#7]
Students will not be able to access this component. Re-edit your component to fix the error.

Error: (1146, "Table 'derex.xblock_config_studioconfig' doesn't exist")

**Comment by silviot** [comment]
The CMS migration was not being run.
Should be fixed in [the latest image](https://github.com/Abstract-Tech/derex.openedx/pull/6/commits/b27229c936e7635b70a62c427486d21bc38c2d7e).

Please run
```
ddc-ironwood pull
ddc-ironwood resetdb
```
to update your local database.
