### ISSUE TITLE
can not export any courses

### ISSUE THREAD

**Issue by laithmassoud** [Abstract-Tech/derex.openedx#8]
Studio's having trouble saving your work
The Studio servers encountered an error

**Comment by silviot** [comment]
The CMS migration was not being run.
Should be fixed in [the latest image](https://github.com/Abstract-Tech/derex.openedx/pull/6/commits/b27229c936e7635b70a62c427486d21bc38c2d7e).

Please run
```
ddc-ironwood pull
ddc-ironwood resetdb
```
to update your local database.
